
name: frontend-cd
on:
  push:
    branches:
      - main
 
jobs:
  Lint_Job:
    runs-on: ubuntu-latest
    defaults:  
     run:
      shell: bash
      working-directory: ./starter/frontend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
         node-version: latest
        
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
         path: ~/.npm
         key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
             
      - name: Install dependencies
        run:  npm ci

      - name: Run Lint 
        run: npm run lint
 
  TEST_JOB: 
    runs-on: ubuntu-latest
    defaults:  
     run:
      shell: bash
      working-directory: ./starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
         node-version: latest
        
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
         path: ~/.npm
         key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
             
    - name: Install dependencies
      run:  npm ci

    - name: Run Lint 
      run: npm run test

  BUILD_JOB: 
    runs-on: ubuntu-latest
    needs: [Lint_Job, TEST_JOB]
    defaults:  
     run:
      shell: bash
      working-directory: ./starter/frontend
    
    steps:
     - name: Check out code
       uses: actions/checkout@v2
    
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

     - name: Build, tag, and push image to Amazon ECR
       env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: frontend
        IMAGE_TAG: build_image
        REACT_APP_MOVIE_API_URL: ${{ secrets.REACT_APP_MOVIE_API_URL }}
       run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg="REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

     - name: Update kube config
       run: aws eks update-kubeconfig --name cluster --region us-east-1

     - name: Deploy to EKS
       run: |
            cd "./k8s/"
            kustomize edit set image frontend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            kustomize build | kubectl apply -f -
            kubectl get svc
            kubectl get pods 
 
